services:
  backend:
    build: .
    ports:
      - "4000:4000"
    environment:
      # - DOPPLER_TOKEN=${DOPPLER_TOKEN}
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
