export enum NotificationEventType {
    ISSUE_CREATED = "ISSUE_CREATED",
    ISSUE_UPDATED = "ISSUE_UPDATED",
    ISSUE_DELETED = "ISSUE_DELETED",
    ISSUE_ASSIGNED = "ISSUE_ASSIGNED",

    PROJECT_CREATED = "PROJECT_CREATED",
    PROJECT_UPDATED = "PROJECT_UPDATED",
    PROJECT_DELETED = "PROJECT_DELETED",
    PROJECT_MEMBER_ADDED = "PROJECT_MEMBER_ADDED",
    PROJECT_ASSIGNED = "PROJECT_ASSIGNED",
    PROJECT_MEMBER_REMOVED = "PROJECT_MEMBER_REMOVED",

    SPRINT_CREATED = "SPRINT_CREATED",
    SPRINT_STARTED = "SPRINT_STARTED",
    SPRINT_UPDATED = "SPRINT_UPDATED",
    SPRINT_DELETED = "SPRINT_DELETED",
    SPRINT_COMPLETED = "SPRINT_COMPLETED",
    NEW_MESSAGE = "NEW_MESSAGE",
    MEETING_SCHEDULED = "MEETING_SCHEDULED",
    MEETING_RESCHEDULED = "MEETING_RESCHEDULED",
    ISSUE_MENTIONED = "ISSUE_MENTIONED"
}