export enum ProjectPermission {
    CREATE_EPIC = "CREATE_EPIC",
    COMPLETE_SPRINT = "COMPLETE_SPRINT",
    CREATE_SPRINT = "CREATE_SPRINT",
    ASSIGN_TASK = "ASSIGN_TASK",
    CREATE_TASK = "CREATE_TASK",
    UPDATE_TASK = "UPDATE_TASK",
}
